<a href="https://colab.research.google.com/github/bbhavishya/BMI-Calculator/blob/branch-1/Count_of_resolver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('/content/Service tickets information_v1.xlsx')

In [10]:
df_copy = df.copy()

In [11]:
df_copy.head()

,SLA,Ticket ID,Created Date,Created By,Description,Priority,Status,Assign To Individual,Last Resolved By,Last Resolved Date,...,Sub Category New,Related Problem Ticket,Resolver,Priority Downgraded,Ticket Severity,SLA Level,Reason for Considering within SLA,Trim,Trim.1,Generic Client
0,09:10:00,300-533083,2022-01-02 18:23:00,"Pungwilai, Ruethai",S1_HJ_TUQ : unable to find 2 order number in w...,High,Resolved,"KS, RAVITEJA","KS, RAVITEJA",2022-01-03 03:33:00,...,Sales Order,NaN,Nagarjuna,No,S3,Met,NaN,Nagarjuna,S3,NaN
1,20:27:00,300-533095,2022-01-03 05:40:00,"Daniels, Renee",S1 HJ ASF - Orders Shipped but not triggered i...,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-04 02:07:00,...,Ship,NaN,Nagarjuna,NO,SR,Met,NaN,Nagarjuna,SR,NaN
2,01:19:00,300-533120,2022-01-03 09:09:00,"SUDHAKAR, RAJENDRAN",HJ: REQUEST EDI FILES FOR MLU,High,Closed,"Khalida Kalis, Mimi","Khalida Kalis, Mimi",2022-01-03 10:28:00,...,SC,NaN,Khalida,NO,SR,Met,NaN,Khalida,SR,NaN
3,07:11:00,300-533136,2022-01-03 10:00:00,"SUDHAKAR, RAJENDRAN",HJ: AUTO REPORT MDU,High,Closed,"Khalida Kalis, Mimi","Khalida Kalis, Mimi",2022-01-03 17:11:00,...,Changes,NaN,Khalida,NO,SR,Met,NaN,Khalida,SR,NaN
4,04:27:00,300-533159,2022-01-03 10:52:00,"Musikul, Waraporn",S1_HJ_Please help to check order 88134766 we c...,High,Closed,"M, Sukudenhen","M, Sukudenhen",2022-01-03 15:19:00,...,Picking,NaN,Sukundhen,No,S3,Met,NaN,Sukundhen,S3,NaN

In [12]:
count = df_copy['Resolver'].value_counts()

In [13]:
count

Khalida       326
Chitra        285
Nagarjuna     264
Raviteja      212
Vimal         207
Alya          205
Raja          140
Aina          124
Sukundhen     104
Usha           81
Phaneendra     32
Nirmal          7
khalida         4
Karthik         1
RAviteja        1
ALya            1
RAJA            1
NAgarjuna       1
CHitra          1
usha            1
chitra          1
Name: Resolver, dtype: int64

In [16]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 28 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   SLA                                1999 non-null   object
 1   Ticket ID                          1999 non-null   object
 2   Created Date                       1999 non-null   datetime64[ns]
 3   Created By                         1999 non-null   object
 4   Description                        1999 non-null   object
 5   Priority                           1999 non-null   object
 6   Status                             1999 non-null   object
 7   Assign To Individual               1999 non-null   object
 8   Last Resolved By                   1999 non-null   object
 9   Last Resolved Date                 1999 non-null   datetime64[ns]
 10  SLA Status                         1999 non-null   object
 11  Resolution                         1991 non-null   object
 12  Notes                              1995 non-null   object
 13  Type                               1999 non-null   object
 14  Application Name                   1999 non-null   object
 15  Team                               1999 non-null   object
 16  Env                                1999 non-null   object
 17  Category                           1999 non-null   object
 18  Sub Category New                   1862 non-null   object
 19  Related Problem Ticket             16 non-null     object
 20  Resolver                           1999 non-null   object
 21  Priority Downgraded                1999 non-null   object
 22  Ticket Severity                    1999 non-null   object
 23  SLA Level                          1999 non-null   object
 24  Reason for Considering within SLA  0 non-null      float64
 25  Trim                               1999 non-null   object
 26  Trim.1                             1999 non-null   object
 27  Generic Client                     0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(24)
memory usage: 437.4+ KB

In [20]:
ravi = df_copy[df_copy.Resolver == 'Raviteja']

In [21]:
ravi.shape

(212, 28)

In [22]:
ravi.head()

,SLA,Ticket ID,Created Date,Created By,Description,Priority,Status,Assign To Individual,Last Resolved By,Last Resolved Date,...,Sub Category New,Related Problem Ticket,Resolver,Priority Downgraded,Ticket Severity,SLA Level,Reason for Considering within SLA,Trim,Trim.1,Generic Client
5,1900-01-01 22:45:00,300-533201,2022-01-03 13:46:00,"Dooa, Shevons",S3 Hj - <Clarins MY> RE: MCL DailyReport,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-05 12:31:00,...,Report,NaN,Raviteja,No,S3,Met,NaN,Raviteja,S3,NaN
23,1900-01-01 00:08:00,300-533351,2022-01-04 12:42:00,"Chomnomchat, Buathong",S1_WMS1_Order isn't available in HJ order numb...,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-05 12:50:00,...,Sales Order,NaN,Raviteja,No,S3,Met,NaN,Raviteja,S3,NaN
49,1900-01-01 01:49:00,300-533515,2022-01-05 12:49:00,"Daniels, Renee",S1 HJ ASF - Multiple Guns Reset,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-06 14:38:00,...,Reset,NaN,Raviteja,NO,SR,Met,NaN,Raviteja,SR,NaN
52,22:10:00,300-533552,2022-01-05 16:31:00,"shakirin, syaqinah",S1 HJ inbound order SVB-OTH5367,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-06 14:41:00,...,Reconciliation Report,NaN,Raviteja,No,S3,Met,NaN,Raviteja,S3,NaN
54,03:13:00,300-533576,2022-01-05 19:30:00,"Production, WLA Admin",SR HJ 7:30PM Healtcheck 1/5/2022,High,Closed,"KS, RAVITEJA","KS, RAVITEJA",2022-01-05 22:43:00,...,Daily Ship Report,NaN,Raviteja,No,SR,Met,NaN,Raviteja,SR,NaN

In [23]:
ravi.to_csv('modified data.csv',index = False)

In [30]:
count_of_resolver = df_copy[df_copy['Resolver'] == 'Raviteja'].shape[0]

In [33]:
print('The number of tickets resolved by Raviteja are : ',count_of_resolver)

The number of tickets resolved by Raviteja are :  212